config/routes.rb
Smartpick::Application.routes.draw do
  resources :compares, only: [:new, :create, :show] do
    get :autocomplete_car_name, :on => :collection
  end
  

  root 'compares#new'

  

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates :name, :uid, presence: true
  validates :uid, uniqueness: true
  has_many :cars
end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :name, :brand, :uid, presence: true
  validates :uid, uniqueness: true
  belongs_to :brand
  has_many :models
end

app/models/compare.rb
class Compare < ActiveRecord::Base
  has_and_belongs_to_many :cars
  validate :presence_of_cars

  def presence_of_cars
    errors[:base] << "Escolha pelo menos um carro para comparar" if self.cars.empty?
  end

  def as_json options
    super({include: {cars: {include: :models}}}.merge(options))
  end
end

app/models/model.rb
class Model < ActiveRecord::Base
  validates :name, :car, :uid, presence: true
  validates :uid, uniqueness: true
  belongs_to :car
  has_many :references

  default_scope { order('name DESC') }

  def year
    name.to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/compares_controller.rb
class ComparesController < ApplicationController
  before_action :set_compare, only: [:show, :edit, :update, :destroy]
  autocomplete :car, :name, full: true

  def new
    @compare = Compare.new
  end

  def create
    @compare = Compare.new(compare_params)
    @compare.car_ids = [params[:car_id_1], params[:car_id_2], params[:car_id_3]]

    respond_to do |format|
      if @compare.save
        format.html { redirect_to @compare, notice: 'Compare was successfully created.' }
        format.json { render action: 'show', status: :created, location: @compare }
      else
        format.html { render action: 'new' }
        format.json { render json: @compare.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_compare
    @compare = Compare.find(params[:id])
  end

  def compare_params
    params[:compare]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compares_helper.rb
module ComparesHelper
end

app/views/compares/_form.html.slim
= form_for(@compare) do |f|
  
  .car-name-1-field
    label Escolha um modelo para inciar a consulta
    = autocomplete_field_tag "car_name_1", '', autocomplete_car_name_compares_path, id_element: '#car_id_1', placeholder: "Toyota Corolla GLi 1.6 16V", id: "car_id_1_field", "data-tooltip" => true, title: "Você pode inserir a marca ou o modelo do carro que deseja comparar", class: "tip-top"
    - if @compare.errors.any?
      small.error Escolha pelo menos um carro para comparar

  .car-name-2-field
    label Escolha um segundo modelo para comparar
    = autocomplete_field_tag "car_name_2", '', autocomplete_car_name_compares_path, id_element: '#car_id_2', placeholder: "Honda Civic Sedan EX 1.6 16V Aut. 4p (nacion.)", id: "car_id_2_field", "data-tooltip" => true, title: "Depois escolha o segundo carro para a comparação", class: "tip-top"

  .car-name-3-field
    label Escolha um terceiro modelo para comparar
    = autocomplete_field_tag "car_name_3", '', autocomplete_car_name_compares_path, id_element: '#car_id_3', placeholder: "Citroën C4 Competition 1.6 Flex 16V 5p Mec.", id: "car_id_3_field", "data-tooltip" => true, title: "Se você quiser ainda pode escolher um terceiro carro para comparar", class: "tip-top"

  = hidden_field_tag "car_id_1"
  = hidden_field_tag "car_id_2"
  = hidden_field_tag "car_id_3"
  .actions
    = f.submit 'Comparar', id: "compare_button"

app/views/compares/new.html.slim
.intro
  h1
    | Busque pelos carros do seu interesse,
    br
    |  e depois compare qual deles vale mais a pena comprar.

.main_box
  .search_icon
    = link_to image_tag("car_search.png"), root_path
  = render 'form'

app/views/compares/show.html.slim
.compares_box
  .row
    .models
      h2
        | Modelos
      .car_names
        - @compare.cars.each do |c|
          p.car_name= c.name
    = link_to 'Fazer nova consulta', root_path

  #compare{data-json=@compare.to_json}

  .row
    .results
      h2 Depreciação ($)
      #depreciation_by_price

  .row
    .results
      h2 Depreciação (%)
      #depreciation_by_percentage

  .row
    .results
      h2 Prejuízo ($)
      #loss_by_price

  .row
    .results
      h2 Prejuízo (%)
      #loss_by_percentage

  .row
    .results
      h2 IPVA (SP)
      #ipva

  .row
    .results
      h2 Custo total
      #total

app/views/layouts/_header.html.slim
header
  .row
    .logo
      = link_to image_tag("logo.png"), root_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Smartpick
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"
    = csrf_meta_tags
    = analytics_init if Rails.env.production?

    meta name="og:title"        content="#{content_for?(:title)       ? yield(:title) : 'Smartpick'}"
    meta name="og:image"        content="#{content_for?(:image)       ? yield(:image) : image_url('smartpick-facebook.png')}"
    meta name="og:type"         content="#{content_for?(:type)        ? yield(:type)  : 'website'}"
    meta name="og:description"  content="#{content_for?(:description) ? yield(:description)  : 'Busque pelos carros do seu interesse, e depois compare qual deles vale mais a pena comprar'}"
    meta name="og:url"          content=request.url

  body class=[controller.controller_name, controller.action_name]
    = render partial: 'layouts/header'
    .row
      = yield
      footer
        = link_to "Contato", "mailto:smartpick.com.br@gmail.com"